/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/about_build_site': RouteRecordInfo<'/posts/about_build_site', '/posts/about_build_site', Record<never, never>, Record<never, never>>,
    '/posts/just_as_this_time': RouteRecordInfo<'/posts/just_as_this_time', '/posts/just_as_this_time', Record<never, never>, Record<never, never>>,
    '/posts/know_about_World': RouteRecordInfo<'/posts/know_about_World', '/posts/know_about_World', Record<never, never>, Record<never, never>>,
    '/posts/learn_about_git': RouteRecordInfo<'/posts/learn_about_git', '/posts/learn_about_git', Record<never, never>, Record<never, never>>,
    '/posts/learn_about_math': RouteRecordInfo<'/posts/learn_about_math', '/posts/learn_about_math', Record<never, never>, Record<never, never>>,
    '/posts/learn_about_python': RouteRecordInfo<'/posts/learn_about_python', '/posts/learn_about_python', Record<never, never>, Record<never, never>>,
    '/posts/what_is_IC': RouteRecordInfo<'/posts/what_is_IC', '/posts/what_is_IC', Record<never, never>, Record<never, never>>,
    '/posts/what_is_Program': RouteRecordInfo<'/posts/what_is_Program', '/posts/what_is_Program', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
